using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace reviews.Models
{
    // Base review properties - matches database structure
    public abstract class ReviewBase
    {
        [Key]
        public int ReviewID { get; set; }           // Auto-generated by database
        public int AccountID { get; set; }          // Customer account ID (not UserID!)
        public int? Rating { get; set; }            // Rating 1-5 (nullable in DB)
        public string? Comment { get; set; }        // Review text (nullable in DB)
        public DateTime CreatedAt { get; set; }     // Auto-set by database
    }

    // Product Review - matches ProductReview table in database
    [Table("ProductReview")]
    public class ProductReview : ReviewBase
    {
        public int ProductID { get; set; }          // Product being reviewed
    }

    // Service Review - matches ServiceReview table in database
    [Table("ServiceReview")]
    public class ServiceReview : ReviewBase
    {
        public int ServiceID { get; set; }          // Service being reviewed
    }
}
